# Generated by Django 2.2.3 on 2020-03-26 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 5, 59, 52, 800149, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
